In [46]:
import torch

In [47]:
a = torch.randn(16, 49, 32)
b = torch.randn(16, 49, 32)
c = torch.randn(16, 49, 32)

In [48]:
r1 = (a @ b.permute(0, 2, 1)) @ c

In [49]:
r2 = torch.einsum("bld,bdl,bld->bld", a, b.permute(0, 2, 1), c)

In [59]:
r3 = torch.einsum("bij,bjd->bid", torch.einsum("bid,bdj->bij", a, b.permute(0, 2, 1)) , c)

In [51]:
r1[0][0]

tensor([-57.5840,   3.7441, -12.1082, -24.1676,  30.8171,  52.8504,  16.4486,
         36.2473, -17.3397, -61.0156, -23.6459, -16.2815,  -5.6858,  39.3005,
         99.7249, -79.1989,   8.6914, -21.3574,  85.9352, -32.1444,  59.3890,
         -5.5889, -76.6860, -18.0191,  38.4080, -14.8143, -67.9317,   6.6015,
          7.1374,  39.7934,  27.8083,  73.7078])

In [52]:
r2[0][0]

tensor([-3.6162e-02, -1.9916e-01,  2.3269e-02, -4.5040e-01,  1.7752e-01,
         1.2133e-01,  3.8320e-01,  1.1200e-03, -3.4468e-01, -2.1230e-01,
         4.6867e-01,  1.7569e-01,  4.1423e-03, -2.4851e-02,  3.1987e-01,
         8.1973e-02, -3.9165e-01, -7.4131e-01, -2.5110e-01, -2.0288e-02,
         5.4359e-01,  3.6856e+00, -6.4270e-02,  2.4648e-01,  1.4166e-01,
        -1.7318e+00, -3.8599e-01,  5.8038e-01, -1.1895e+00,  6.3403e-01,
        -2.7671e-01, -1.3566e-01])

In [60]:
r3[0][0]

tensor([-57.5840,   3.7441, -12.1082, -24.1676,  30.8171,  52.8504,  16.4486,
         36.2473, -17.3397, -61.0156, -23.6459, -16.2815,  -5.6858,  39.3005,
         99.7249, -79.1989,   8.6914, -21.3574,  85.9352, -32.1444,  59.3890,
         -5.5889, -76.6860, -18.0191,  38.4080, -14.8143, -67.9317,   6.6015,
          7.1374,  39.7934,  27.8083,  73.7078])

In [57]:
(a @ b.permute(0, 2, 1))[0][0]

tensor([  0.4912,  11.2430,   1.4899,  -3.4315,  -8.8541,  -6.2841,  -9.6530,
          7.9916, -11.3729,   8.9488,   9.4520,  -3.8039,  -0.9285,   4.6581,
         -7.4912,  -2.7731,   4.8104,   7.1135,  20.7079,   2.9880,   0.4874,
         -9.9207,  -1.0072,   5.7786,   5.4767,  -4.5774,  -6.9229,  -5.5188,
          9.1612,  -6.5908,  -3.7144,   4.3445,   0.4608,  -4.8475,   8.7826,
          9.3364,  -5.4685,   7.1195,   8.2237, -10.6565,  -6.9872,  -1.4654,
          6.8857,   2.8886,  -1.5983,  -0.4504,   7.4060,   1.9466, -10.6994])

In [58]:
torch.einsum("bid,bdj->bij", a, b.permute(0, 2, 1))[0][0]

tensor([  0.4912,  11.2430,   1.4899,  -3.4315,  -8.8541,  -6.2841,  -9.6530,
          7.9916, -11.3729,   8.9488,   9.4520,  -3.8039,  -0.9285,   4.6581,
         -7.4912,  -2.7731,   4.8104,   7.1135,  20.7079,   2.9880,   0.4874,
         -9.9207,  -1.0072,   5.7786,   5.4767,  -4.5774,  -6.9229,  -5.5188,
          9.1612,  -6.5908,  -3.7144,   4.3445,   0.4608,  -4.8475,   8.7826,
          9.3364,  -5.4685,   7.1195,   8.2237, -10.6565,  -6.9872,  -1.4654,
          6.8857,   2.8886,  -1.5983,  -0.4504,   7.4060,   1.9466, -10.6994])

In [12]:
b.T.shape

torch.Size([32, 49, 16])

In [8]:
torch.einsum("bld,bdl,bld->bld", torch.randn(16, 49, 32), torch.randn((16, 49, 32)).permute(0, 2, 1), torch.randn((16, 49, 32))).shape


torch.Size([16, 49, 32])

In [5]:
torch.randn((16, 49, 32)).permute(0, 2, 1)

tensor([[[-0.3704,  1.4032, -0.7048,  ..., -0.4132, -0.3949, -0.8504],
         [ 0.3695,  0.2494,  0.8463,  ..., -1.1315, -0.4157,  0.8673],
         [ 0.2926,  1.9813,  0.3456,  ...,  0.1091, -0.6155, -1.3210],
         ...,
         [-0.0822, -0.5912,  0.9518,  ..., -0.0055, -0.4127,  2.2911],
         [ 0.4493,  0.6933,  0.6695,  ..., -0.5338,  0.7737,  1.0059],
         [-1.0822,  0.3267, -1.3029,  ...,  0.3172, -0.0760,  0.0883]],

        [[-0.3819,  1.0652, -1.2934,  ...,  0.0221,  1.1569,  0.3976],
         [ 0.7875,  0.6365,  0.9404,  ...,  2.0551, -1.1833,  0.0214],
         [-1.0740, -0.1261, -1.7568,  ..., -0.2903,  0.1767, -0.6691],
         ...,
         [ 0.2984,  0.4384,  0.0098,  ...,  1.5355,  1.4060, -1.4047],
         [-0.2919, -0.1221,  1.1431,  ...,  0.4948, -0.9033, -0.5767],
         [-1.7111, -0.2460, -0.2173,  ...,  1.1455,  1.5220, -1.0221]],

        [[-0.8388, -1.0151, -0.8340,  ..., -0.3851,  0.0474,  1.0408],
         [ 0.7618, -0.4939, -1.3375,  ...,  0

In [63]:
U, S, Vh = torch.svd(a)

In [64]:
U.shape, S.shape, Vh.shape

(torch.Size([16, 49, 32]), torch.Size([16, 32]), torch.Size([16, 32, 32]))

In [5]:
a = [1, 5, 6,7,8, 0.7, 9,393, 4]

In [6]:
import numpy as np

In [7]:
np.argmin(a)

5